### PR TITLE
Add hardware acceleration setting

### PR DESCRIPTION
**Pull request by BenCheung0422**
By default, hardware acceleration is not enabled. With help of #523, this could further reduce around 10%-15% CPU usage (with using GPU) when hardware acceleration is enabled.

### CODE REVIEW

**Review by Makkkkus — CHANGES_REQUESTED** [review]
You don't have use this as a normal setting.

**Comment by BenCheung0422** [comment]
Is it because it applies only on startup?

**Comment by Makkkkus** [comment]
Yeah, you could make it possible to be disabled by a launch argument.

**Comment by BenCheung0422** [comment]
For convenience, it could be a setting that require a restart with modified value.

**Comment by Makkkkus** [comment]
No, using a launch argument would be more convenient. Both in code and use.

**Comment by BenCheung0422** [comment]
Then, a launching argument modifying setting value.

**Comment by Makkkkus** [comment]
Don't use the Settings class. That will just be confusing.

**Comment by BenCheung0422** [comment]
The entire setting is removed from settings and preferences. It can now only be disabled by using a flag.

**Comment by Makkkkus** [comment]
You haven't fixed this yet. You need to revert the changes related to saving and remove a reference to the setting in OptionsMainMenuDisplay.

**Comment by BenCheung0422** [comment]
Ok.

**Review by ChristofferHolmesland — APPROVED** [review]

**Review by Makkkkus — APPROVED** [review]

**Pull request merged**
