### PR TITLE
Fix problems caused by a revert in FPS entry change

### PR DESCRIPTION
**Pull request by BenCheung0422**
A change in FPS entry made by #425 has been reverted by https://github.com/MinicraftPlus/minicraft-plus-revived/commit/9de1e2a200cec588d80e21d9a2bd4b3df976104d, but the change has already been proposed in 2.2.0-dev3, which may cause potential compatibility problem, so this fixes this problem, also redoes a change by #457 and a change from interval of 1 to 10 in FPS setting values.

### CODE REVIEW

**Comment by Makkkkus** [comment]
You're fixing problems that you caused yourself with the major change you made yourself. Just change your settings file.

**Comment by BenCheung0422** [comment]
Em...that has been released in a pre-release. Aren't we ensuring the compatibility in each pre-release?

**Comment by Makkkkus** [comment]
Nope. They're pre-releases. Or we can just delete it.

**Comment by BenCheung0422** [comment]
Delete what?

**Pull request closed without merging**
