### PR TITLE
Update ore tile textures

### PR DESCRIPTION
**Pull request by BenCheung0422**
Update the textures of the ore tiles depending on their item textures.
Also, trim the height requirement of skin images from 32 to 16 as the second row is not used.

### CODE REVIEW

**Comment by Makkkkus** [comment]
I don't think this is neccecary. All of the changes seemingly only remove details from the textures.

**Review by Makkkkus — APPROVED** [review]

**Comment by Makkkkus** [comment]
Add it to changelog maybe.

**Comment by BenCheung0422** [comment]
Putting it to release changelog might be weird if you talking about the textures.
I will add the skin part.

**Review by Litorom — CHANGES_REQUESTED** [review]
Please Update all relating items to the new color scheme. This includes tools, armor, weapons, and totem of air. Please also improve the shape of the ingots; they don’t look right.

**Review by ChristofferHolmesland — APPROVED** [review]
I like the changes :)

**Review by Makkkkus — APPROVED** [review]
Yeah, forgot about this. This is good.

**Pull request merged**
