### PR TITLE
Update splash screen coloring

### PR DESCRIPTION
**Pull request by BenCheung0422**
First, there is only black background used in the current splash screen. Second, the speed of the fading is now constant and not depending on the looping speed. Also, the fading calculation problem on the alpha channel is now fixed, so it would now fade as expected. The faded in screen now holds at least 180ms before fading out even if background execution is finished. The whole fading process: fading in (306ms) -> holding (at 180ms least until background process finishes) -> fading out (360ms).

### CODE REVIEW

**Comment by Litorom** [comment]
Can you add a gif of the new splash, I can’t download/run code on an iPad. (I wish I could tho)

**Comment by BenCheung0422** [comment]
https://github.com/MinicraftPlus/minicraft-plus-revived/assets/74168521/b3412399-d279-4f2c-b9a6-1eae577ed7af

**Comment by BenCheung0422** [comment]
There is a player mentioned that:

> I don't like the rainbow color effect of the startup, idk why, It's maybe because of the color saturation
> I don't like the new rainbow startup
> i feel like it doesn't fit at all with the game
> a black startup with the logo slowly appearing and then shinning would be better in my opinion
> (and after shinning slowly disappearing again to lead to the main menu)

**Comment by BenCheung0422** [comment]
Also, this includes the fixes on calculations that the algorithms do not meet the actual results.

**Comment by BenCheung0422** [comment]
Why is it pointless and should not be included?

**Comment by BenCheung0422** [comment]
I have entirely simplified the splash screen. See the updated description.

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/74168521/f38d11b7-23a1-4094-ad01-b98540168d00

**Comment by Makkkkus** [comment]
I don't trust that this works cross-platform.

1. bloat
2. keep to the roadmap

**Comment by BenCheung0422** [comment]
What do you mean by "works cross-platform"?

**Pull request closed without merging**
