### PR TITLE
Fix ResourcePackDisplay entry reposition problem when moving entries

### PR DESCRIPTION
**Pull request by BenCheung0422**
This rendering occurs when moving entries within the resource pack display menu. The rendering is because the menus are not correctly repositioned when updated.
~~Note: ~~#533~~ is required to test this.~~(outdated)

### CODE REVIEW

**Comment by Litorom** [comment]
I can't figure out how to active a resource pack

**Review by Makkkkus — COMMENTED** [review]
Why do you use bitwise operators here? That's a bug magnet!

**Comment by BenCheung0422** [comment]
To active a resource pack, hold your shift and use you cursor on the selected pack to the right.

**Comment by Litorom** [comment]
> To active a resource pack, hold your shift and use you cursor on the selected pack to the right.

You should really change that, too confusing and the instructions are off the screen. Idk how that will work with controllers.

**Comment by BenCheung0422** [comment]
I thought that is intuitive enough when there is an instruction on the screen.

**Comment by BenCheung0422** [comment]
However, it is the most direct way I can find to implement this.

**Comment by Makkkkus** [comment]
> To active a resource pack, hold your shift and use you cursor on the selected pack to the right.

Just use the enter button in the same way you add items to a chest. Why does it have to be different??

And instructions should be on the screen.

**Comment by BenCheung0422** [comment]
About tweaking this, as this is not what this pull request should be doing, later I will include such change in #581.

**Comment by BenCheung0422** [comment]
And also, this is the instruction to move pack by holding shift, although it is out of screen. #543 should have solved this problem. It should not be shorten, and breaking the line is not a neat and great way.

image

**Comment by Litorom** [comment]
Only fixes positioning, approved

**Pull request merged**
