### PR TITLE
Ru lang

### PR DESCRIPTION
**Pull request by Domaman202**

### CODE REVIEW

**Comment by Litorom** [comment]
I think that we should have a separate font sheet

**Comment by Makkkkus** [comment]
Russian characters seem good, but the translation work seems sloppy. I've also heard that there is swearing in the loc.

Invalid.

**Comment by Domaman202** [comment]
\=

**Comment by Domaman202** [comment]
slander.

**Comment by Makkkkus** [comment]
I didn't intend for you to close this, I just requested some better work on the translation. We would gladly implement the features that we deem optimal for adoption.

**Pull request closed without merging**
