### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BenCheung0422**
This updates the SVG from a cache from a workflow into an immediate response from API, then works are reduced. Also, the link is changed from a invite link into a stats site having a link to join localization.

### CODE REVIEW

**Comment by Makkkkus** [comment]
This is pretty neat. Good job. Could you add the possibility to join the project though the website?

**Comment by BenCheung0422** [comment]
Yes. There is a button with a pencil icon at the top-right corner titled "contribute on POEditor".

**Comment by Makkkkus** [comment]
I meant a button with text on it that isn't hidden in the corner. Perhaps by making the titles of the cards hyperlinks?

**Comment by BenCheung0422** [comment]
I have added these buttons at the top of the main page. Since there is a limitation for the API to obtain the links for a specific language even language IDs, I would not add links to the cards for the corresponding languages.

**Comment by Makkkkus** [comment]
I don't see any changes. You could add a header element that says "Contribute".

**Comment by BenCheung0422** [comment]
I have forgotten deploying to production. It should apply now.

**Review by Makkkkus — APPROVED** [review]

**Review by ChristofferHolmesland — APPROVED** [review]

**Pull request merged**
