### PR TITLE
fix: fix connected tiles requiring flipped sprites

### PR DESCRIPTION
**Pull request by maxkratt**
This fixes all connected tiles (grass, holes, walls, etc.) from needing flipped sprites in order to be displayed correctly. And also fixes the problem introduced in 8881490686ad9705b637af87ba6de0afa05f2a46 where grass, hole, sand, water, and lava tiles have been incorrectly rotated 180°.

### CODE REVIEW

**Review by TheBigEye — CHANGES_REQUESTED** [review]
I think that the other textures (24x24) such as the Water and Lava connectors, Grass, Walls, etc, should also be rotated 180 degrees in the spritesheet, since in the game, these are positioned slightly differently

**Comment by BenCheung0422** [comment]
The handling way is going to be changed: #395.

**Comment by maxkratt** [comment]
> * I think that the other textures (24x24) such as the Water and Lava connectors, Grass, Walls, etc, should also be rotated 180 degrees in the spritesheet, since in the game, these are positioned slightly differently
> 
>     * The ExplodedTile code needs to be modified as well (removing the last "3" in the sprite), as there is a bug that causes the white part of the explosion to display incorrectly

I don't know exactly what you mean about the grass, walls, water, and lava connectors. But I didn't rotate them in the spritesheet because they are already facing the correct way. I flipped the rock, hardrock, and cloud tiles in the spritesheet because they were upsidedown.
Regarding the ExplodedTile, I believe you are right about the mirror parameter, though I haven't noticed any bugs with its display.



> The handling way is going to be changed: #395.

I didn't realize this, my mistake. However the visual problems fixed by this commit are not yet fixed in #395.

**Review by TheBigEye — APPROVED** [review]
> I don't know exactly what you mean about the grass, walls, water, and lava connectors. But I didn't rotate them in the spritesheet because they are already facing the correct way. I flipped the rock, hardrock, and cloud tiles in the spritesheet because they were upsidedown. Regarding the ExplodedTile, I believe you are right about the mirror parameter, though I haven't noticed any bugs with its display.

- Sorry, now I just realized my mistake, now compare the positions of the tiles, between Minicraft (ld22), Minicraft plus 1.9.1 and Minicraft plus (this change)
- When I refer to the walls, I mean the sprites (24x24) of the Brick and Obsidian Walls (possibly this also affects the Plank Walls), since, now they appear upside down and previously they were correctly

**Comment by TheBigEye** [comment]
> I don't know exactly what you mean about the grass, walls, water, and lava connectors
When I refer to the walls, I mean the sprites (24x24) of the Brick and Obsidian Walls (possibly this also affects the Plank Walls), since, now they appear upside down and previously they were correctly

**Review by BenCheung0422 — DISMISSED** [review]
This is handled by [this commit from #395](https://github.com/MinicraftPlus/minicraft-plus-revived/pull/395/commits/fd22534e10567b76674029cf631ead1eb420b907)

**Comment by Makkkkus** [comment]
> This is handled by [this commit from #395](https://github.com/MinicraftPlus/minicraft-plus-revived/pull/395/commits/fd22534e10567b76674029cf631ead1eb420b907)

No, that's not a nice thing to do. It is way better to use this pull request.

**Comment by BenCheung0422** [comment]
Okay, so when this pull request is being merged, #395 will replace it.

**Comment by maxkratt** [comment]
>     * Sorry, now I just realized my mistake, now compare the positions of the grass tiles, between Minicraft (ld22), Minicraft plus 1.9.1 and Minicraft plus (this change)
> 
>     * When I refer to the walls, I mean the sprites (24x24) of the Brick and Obsidian Walls (possibly this also affects the Plank Walls), since, now they appear upside down and previously they were correctly

You were right about the stone and obsidian wall tiles; I have fixed them per your advise. The wood wall is symmetrical and didn't need changing.
I have also corrected the mirroring of the exploded tile.
___
Regarding the grass tiles, I have now noted differences that I think you are referring to.
The original grass tile present in the (ld22) version and possibly older versions of Minicraft+ had a light top and left side and a dark right and bottom side.
original-grass-tile

Somewhere in 1.9.1 or prior the sprite right and bottom was not displayed.
grass-error-caused-prior-to-1-9-1

1.9.4-dev1 fixed the missing side and bottom, but it removed the darker part of the grass tile.
missing-shadow

And finally 1.9.4-dev6 flipped the tiles around.
flipped-tiles

It is also possible you noticed the change in the water meeting dirt texture that took place in 2.0.6-dev4, but as it is unrelated to this pull request I have not done anything about it.

I have not re-added the dark shadow on the grass tile that was present in the original game, should I?

**Comment by Makkkkus** [comment]
> I have not re-added the dark shadow on the grass tile that was present in the original game, should I?

I think that's a good idea.

**Comment by maxkratt** [comment]
I have added the missing shadow on the grass tile as suggested.

> Okay, so when this pull request is being merged, #395 will replace it. Please first resolve the problems that @TheBigEye mentioned.

All the problems have now been resolved.

**Review by Makkkkus — APPROVED** [review]

**Pull request merged**
