### PR TITLE
Resolves #329

### LINKED ISSUE #329: Prevent achievements from being obtained in creative mode
**Describe the bug**
Achievements can be achieved in creative mode.

Side note: Achievement text overflows off screen if too long. Going down to the gem level will trigger this.

**To Reproduce**
1. Open a creative mode world
2. Attempt to achieve an achievement
3. Achievement is obtained

**Expected behavior**
It is not obtained.

**Screenshots**
Screen Shot 2022-04-29 at 8 41 28 AM

### PR DESCRIPTION
**Pull request by BenCheung0422**
This should Resolve #329

### CODE REVIEW

**Comment by lino-levan** [comment]
Don't reformat the files. It creates a bunch of noise that makes it hard to see what has been changed.

**Review by Makkkkus — CHANGES_REQUESTED** [review]
Instead of adding an if statement every time we want to give the player an achievement, we should simply add an `if (Game.isMode("creative")) return;` to setAchievement().

I will also add that the current title for the pull request doesn't tell us anything on a first glance, so you don't know what the pull request is about before you check the linked issue. Issues should never be linked in titles; there is a reason why the number is blue in the description but not the title.

Keep the formatting changes though.

**Comment by lino-levan** [comment]
> Instead of adding an if statement every time we want to give the player an achievement, we should simply add an `if (Game.isMode("creative")) return;` to setAchievement().

I'm not sure if this is the best way to do this? There are some achievements that are not achieved in-game but in the menu. Maybe it's a overloaded method where there's a boolean flag to check whether or not it's in creative?

**Comment by Makkkkus** [comment]
In that case change it to `if (checkCreative && Game.isMode("creative")) return;` and add that argument to the function.

**Comment by Litorom** [comment]
I have an idea of how to do this.

**Comment by Litorom** [comment]
Made PR #332

**Pull request closed without merging**
