### PR TITLE
Update ChangeLog.txt

### PR DESCRIPTION
**Pull request by BenCheung0422**
Add 2.2.0 change log.

### CODE REVIEW

**Review by Makkkkus — CHANGES_REQUESTED** [review]
"Obsidian knight" should not be capitalised.

**Review by Makkkkus — APPROVED** [review]

**Review by Litorom — CHANGES_REQUESTED** [review]
Remove Controller Support, it’s a bit buggy. Doesn’t affect normal gameplay therefore it’s fine if it’s coded in and published.

**Comment by BenCheung0422** [comment]
@Litorom I think maybe it still can be kept until the change of the system. As you said that it doesn't affect normal gameplay.

**Comment by Litorom** [comment]
> @Litorom I think maybe it still can be kept until the change of the system. As you said that it doesn't affect normal gameplay.

No because if a user knows there is controller support when it isn’t finished.

**Review by Litorom — APPROVED** [review]
Okay, that’s better.

**Pull request merged**
